### ISSUE TITLE
Output level?

### ISSUE THREAD

**Issue by PA3AEF** [DeonMarais64/PlutoPlusSDR-FW#2]
Hi, Deon great job you did on the FW!! 
I am trying to figure out what output level the Pluto Plus has. Cannot find anything on the internet. Do you perhaps have any information?

regards,
Peter

PS. Apologies for usign the issue list for this, but I can't find anywhere else active Pluto Plus 
users ;-(

**Comment by DeonMarais64** [comment]
Hi Peter,
I am not aware of any reference characterizing the `Pluto+` output. 
In absence of such, the best I have been able to surmise is as follows,

Looking at what is available for the `PlutoSDR`, from [here](https://wiki.analog.com/university/tools/pluto/users/transmit#transmit_performance) and then comparing the manufacturer claimed characteristic's of Balun's used on `PlutoSDR` and `Pluto+`, `TCM1-63AX` and `B0310J50100AHF` respectively it looks to me that both output levels should be similar for just about all intents and purposes.

I have two `Pluto+`'s and unfortunately do not have access to any official ADI `PlutoSDR`'s. However, it seems to me from my general use of the `Pluto+`'s I have that the output levels are indeed very similar to that shown in the reference for the `PlutoSDR`.

[See also](https://github.com/plutoplus/plutoplus/issues/13) and [here](https://www.rtl-sdr.com/tech-minds-testing-the-pluto-plus-sdr/) (see the comments at the bottom of the article).

**Comment by PA3AEF** [comment]
Thanks Deon for your pointers. They are very helpful. Output seems the same as the standard Pluto.
